import pandas as pd

# df = pd.read_csv("StudentsPerformance.CSV")
df = pd.read_csv("titanic.csv")
# print((stud.iloc[0:7]))
# print((stud.loc[:7]))
# print((stud.iloc[:7]))
# print((stud.tail(7)))
# print((stud.head(7)))
# print((stud.loc[:6]))
# print(df.index)
# print()
# print(df.columns)
# print()
# print(df.shape)
# print()
# print(df.dtypes)
# print()
# # print(df.get_dtype_counts().index)
# # print(df.select_dtypes(include='int', exclude='str'))
# print(df.size)
print(df.shape)
print(df.dtypes)